### ISSUE TITLE
awesome stuff! any realtime soundcapture possible?

### ISSUE THREAD

**Issue by nyov** [juanmv94/Soniqueviewer#1]
This is awesome. Generally I preferred (and still do) the [WinAMP **_vis_avs_**](https://github.com/visbot/vis_avs) visualizations (not the MilkDrop / projectM stuff); because they were generally cooler 3D stuff, could be modded in realtime and could change the render resolution. I guess many people didn't know about those because milkdrop was the default vis plugin.

But I also had and ran [Sonique](https://www.afterdawn.com/news/article.cfm/2019/07/31/sonique-vs-winamp-the-era-of-windows-software-appearance-customizations) on and off, for those vis. I just grabbed it again and some avs to try this out.

Great stuff! I just wish it could work natively on linux, but I know those VIS are windows DLLs, and would need to be wrapped somehow. For now it works just fine with WINE SDL.

Would it be possible to add the ability to capture live sound source input through SDL, instead of a pre-rendered waveform, though? I suppose that's only possible if the algorithm to render those waveforms is known, instead of just dumping sonique`s.
 That'd be the icing on the cake, though!

(p.s.> you mis-spelled "effect" all throughout your code)

**Comment by nyov** [comment]
Apparently Tuniac is an open source mediaplayer by some old Sonique devs? It has code for sonique-style svp vis' that might be useful to any code hackers: https://sourceforge.net/p/tuniac/code/HEAD/tree/Tuniac1/SVPVisualPlugin/ .
But also win-only.

**Comment by juanmv94** [comment]
Sonique visualizations can also change resolution: it's one of theparameters that can be passed to the executable (**-r**)

As you mention, VIS files are DLL Windows files, and that's the reason I could only make a Windows version using WIN32 API call
`HINSTANCE hGetProcIDDLL = LoadLibrary(argv[1]);`

I don't know about the algorithms used by sonique to generate both **spectrum** and **waveform**. It could be dissasembled, or implement similar ones, but I wanted to keep the project this simple.

**Comment by mccann** [comment]
@juanmv94 For what it's worth, the waveform is just the PCM data, and the spectrum was just the energy values from an FFT. There wouldn't be any need to for it to be bit-perfect.  (If recall correctly, on early versions of Sonique I used the spectrum data from MP3 decoder (DCT coefficients) when playing mp3, not sure if that was true in the later versions, was a long time ago)
